shopapp.webui/Controllers/CartController.cs
/*
* This class is used to manage the cart operations.
* It is used to add, delete, and display the cart items.
* It is also used to checkout the cart items and get the orders of the user.
*/
using System;
using System.Collections.Generic;
using System.Linq;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;
using shopapp.entity;
using shopapp.webui.Extensions;
using shopapp.webui.Identity;
using shopapp.webui.Models;

namespace shopapp.webui.Controllers
{
    // This attribute is used to allow only authorized users to access the methods of this class.
    [Authorize]
    public class CartController: Controller
    {
        // Declare the ICartService, UserManager, and IOrderService interfaces.
        private readonly ICartService _cartService;
        private readonly UserManager<User> _userManager;
        private readonly IOrderService _orderService;

        // Constructor method is used to inject the ICartService, UserManager, and IOrderService interfaces.
        public CartController(ICartService cartService, UserManager<User> userManager, IOrderService orderService)
        {
            _cartService = cartService;
            _userManager = userManager;
            _orderService = orderService;
        }
        
        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            // Create a CartModel object and assign the cart items to it.
            return View(new CartModel() {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(i => new CartItemModel() {
                    CartItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.Name,
                    Price = (double)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity
                }).ToList()
            });
        }

        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity)
        {
            var userId = _userManager.GetUserId(User);
            _cartService.AddToCart(userId, productId, quantity);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteFromCart(int productId)
        {
            var userId = _userManager.GetUserId(User);
            _cartService.DeleteFromCart(userId, productId);

            return RedirectToAction("Index");
        }

        public IActionResult Checkout() {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));

            // Create an OrderModel object and assign the cart items to it.
            var orderModel = new OrderModel
            {
                CartModel = new CartModel()
                {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(i => new CartItemModel()
                    {
                        CartItemId = i.Id,
                        ProductId = i.ProductId,
                        Name = i.Product.Name,
                        Price = (double)i.Product.Price,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity = i.Quantity,
                    }).ToList()
                }
            };
            return View(orderModel);
        }

        // This method is used to checkout the cart items.
        [HttpPost]
        public IActionResult Checkout(OrderModel model)
        {
            if(ModelState.IsValid) {
                // Get the user id.
                var userId = _userManager.GetUserId(User);
                // Get the cart items of the user.
                var cart = _cartService.GetCartByUserId(userId);

                // Create a CartModel object and assign the cart items to it.
                model.CartModel = new CartModel() {
                    CartId = cart.Id,
                    CartItems = cart.CartItems.Select(i => new CartItemModel()
                    {
                        CartItemId = i.Id,
                        ProductId = i.ProductId,
                        Name = i.Product.Name,
                        Price = (double)i.Product.Price,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity = i.Quantity,
                    }).ToList()
                };
                
                // Create a Payment object and assign the payment process to it.
                var user = _userManager.FindByIdAsync(userId).Result;
                var payment = PaymentProcess(model, user);

                // If the payment is successful, save the order and clear the cart.
                if(payment.Status == "success")
                {
                    SaveOrder(model, payment, userId);
                    ClearCart(model.CartModel.CartId);
                    // If the password is reset successfully, send a message and redirect the user to the login page
                    TempData.Put("message", new AlertMessage() {
                        Title = "Order Placed.",
                        Message = "Your order has been placed successfully.",
                        AlertType = "success"
                    });
                    return View("Success");
                } else {
                    TempData.Put("message", new AlertMessage() {
                        Title = "Payment Error.",
                        Message = payment.ErrorCode + " - " + payment.ErrorMessage,
                        AlertType = "danger"
                    });
                }
            }
            return View(model);
        }

        public IActionResult GetOrders() {
            var userId = _userManager.GetUserId(User);
            var orders = _orderService.GetOrders(userId);

            var orderListModel = new List<OrderListModel>();
            OrderListModel orderModel;

            foreach (var order in orders) {
                // Create an OrderListModel object and assign the order items to it.
                orderModel = new OrderListModel
                {
                    OrderId = order.OrderId,
                    OrderNumber = order.OrderNumber,
                    OrderDate = order.OrderDate,
                    FirstName = order.FirstName,
                    LastName = order.LastName,
                    Phone = order.Phone,
                    Email = order.Email,
                    Address = order.ShippingAddress.Address + " " + order.ShippingAddress.City + "/" + order.ShippingAddress.Country,
                    Note = order.Note,
                    PaymentType = order.PaymentType,
                    OrderState = order.OrderState,

                    // Create an OrderItemModel object and assign the order items to it.
                    OrderItems = order.OrderItems.Select(i => new OrderItemModel()
                    {
                        OrderItemId = i.Id,
                        Name = i.Product.Name,
                        Price = (double)i.Price,
                        Quantity = i.Quantity,
                        ImageUrl = i.Product.ImageUrl
                    }).ToList()
                };

                orderListModel.Add(orderModel);

            }
            return View("Orders", orderListModel);
        }

        private void ClearCart(int cartId)
        {
            _cartService.ClearCart(cartId);
        }

        // Save order to the database.
        private void SaveOrder(OrderModel model, Payment payment, string userId)
        {
            // Create an Order object and assign the order items to it.
            var order = new Order
            {
                OrderNumber = new Random().Next(100000, 999999).ToString(),
                OrderState = EnumOrderState.completed,
                PaymentType = EnumPaymentType.CreditCard,
                PaymentId = payment.PaymentId,
                ConversationId = payment.ConversationId,
                OrderDate = DateTime.Now,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                Phone = model.Phone,
                UserId = userId,
                Note = model.Note,
                OrderItems = new List<entity.OrderItem>(),
                ShippingAddress = new ShippingAddress
                {
                    City = model.ShipModel.City,
                    Country = model.ShipModel.Country,
                    Address = model.ShipModel.Address,
                    ZipCode = model.ShipModel.ZipCode
                },
                BillingAddress = new BillingAddress
                {
                    City = model.BillModel.City,
                    Country = model.BillModel.Country,
                    Address = model.BillModel.Address,
                    ZipCode = model.BillModel.ZipCode
                },
                Card = new entity.Card
                {
                    CardName = model.CardModel.CardName,
                    CardNumber = model.CardModel.CardNumber,
                    ExpirationMonth = model.CardModel.ExpirationMonth,
                    ExpirationYear = model.CardModel.ExpirationYear,
                    Cvc = model.CardModel.Cvc
                }
            };

            foreach (var item in model.CartModel.CartItems)
            {
                var orderItem = new entity.OrderItem()
                {
                    Price = item.Price,
                    Quantity = item.Quantity,
                    ProductId = item.ProductId
                };
                
                order.OrderItems.Add(orderItem);
            }
            _orderService.Create(order);
        }

        private Payment PaymentProcess(OrderModel model, User user)
        {
            Options options = new Options
            {

shopapp.webui/Controllers/ShopController.cs
/*
* This class is used to control the shop page.
* It is used to display the products in the shop page.
*/

using System.Linq;
using Microsoft.AspNetCore.Mvc;
using shopapp.business.Abstract;
using shopapp.entity;
using shopapp.webui.Models;

namespace shopapp.webui.Controllers
{
    public class ShopController:Controller
    {
        private readonly IProductService _productService;

        public ShopController(IProductService productService) {
            _productService = productService;
        }

        // List the products
        public IActionResult List(string category, int page = 1) {
            const int pageSize = 3;
            // Create a new ProductListViewModel object
            var productViewModel = new ProductListViewModel {
                PageInfo = new PageInfo() {
                    TotalItems = _productService.GetCountByCategory(category),
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    CurrentCategory = category
                },
                Products = _productService.GetProductsByCategory(category,pageSize, page)
            };
            return View(productViewModel);
        }

        // Display the details of a product
        public IActionResult Details(string url) {
            if (url == null) {
                return NotFound();
            }

            // Get the product details using the url
            Product product = _productService.GetProductDetails(url);

            if (product == null) {
                return NotFound();
            }

            return View(new ProductDetailModel() {
                Product = product,
                Categories = product.ProductCategories.Select(i=>i.Category).ToList()
            });
        }

        // Search for a product using a search query by product name and description
        public IActionResult Search(string q) {
            q ??= ""; // If q is null, set it to an empty string
            var productViewModel = new ProductListViewModel {
                Products = _productService.GetSearchResult(q)
            };
            return View(productViewModel);
        }
    }
}

shopapp.webui/Views/Shop/Details.cshtml
@model ProductDetailModel

<div class="row mt-3">
    <div class="col-md-3">
        <img src="~/img/@Model.Product.ImageUrl" alt="" class="img-fluid">
    </div>
    <div class="col-md-9">
        <div class="card-body">
            <h3 class="mb-3">@Model.Product.Name</h3> <hr>
            
            @foreach (var item in Model.Categories)
            {
                <a asp-controller="Shop" asp-action="list" asp-route-category="@item.Url" class="btn btn-link p-0 mb-3">@item.Name</a>
            }
            
            <div class="mb-3">
                <h4 class="text-primary mb-3"> <i class="fas fa-turkish-lira-sign">
                </i> @Model.Product.Price</h4>
                <form asp-controller="Cart" asp-action="AddToCart" method="POST" class="form-inline">
                    <input type="hidden" name="productId" value="@Model.Product.ProductId"/>
                    <div class="input-group mb-3">
                        <input type="number" name="quantity" class="form-control" value="1" min="1" step="1" max="100" style="width: 100px;"/>
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-cart-plus"></i> Add to Cart
                            </button>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 p-5">
        <p class="p-3">@Html.Raw(Model.Product.Description)</p>
    </div>
</div>

shopapp.webui/Views/Shop/List.cshtml
@model ProductListViewModel

@{
    var Page = Model.PageInfo;
}

<div class="row mt-3">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
        <partial name="_search" />
    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach (var product in Model.Products)
            {
                <div class="col-md-4">
                    @await Html.PartialAsync("_product", product)
                </div>
            }
        </div>

        <div class="row">
            <nav aria-label="Page navigation example">
                <ul class="pagination">

                    <li class="page-item">
                        @if(String.IsNullOrEmpty(Page.CurrentCategory)) {
                            <a class="page-link" href="/products?page=@(Page.CurrentPage > 1?(Page.CurrentPage - 1):Page.CurrentPage)" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        } else {
                            <a class="page-link" href="/products/@(Page.CurrentCategory)?page=@(Page.CurrentPage > 1?(Page.CurrentPage - 1):Page.CurrentPage)" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        }
                    </li>

                    @for (int i = 1; i <= Page.TotalPages(); i++)
                    {
                        @if(String.IsNullOrEmpty(Page.CurrentCategory)) {
                            <li class="page-item @(Page.CurrentPage == i ? "active":"")">
                                <a class="page-link" href="/products?page=@i">@i
                                </a>
                            </li>
                        } else {
                            <li class="page-item @(Page.CurrentPage == i ? "active":"")">
                                <a class="page-link" href="/products/@Page.CurrentCategory?page=@i">@i
                                </a>
                            </li>
                        }
                    }
                    <li class="page-item">
                        @if(String.IsNullOrEmpty(Page.CurrentCategory)) {
                            <a class="page-link" href="/products?page=@(Page.CurrentPage < Page.TotalPages() ?(Page.CurrentPage + 1):Page.CurrentPage)" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        } else {
                            <a class="page-link" href="/products/@(Page.CurrentCategory)?page=@(Page.CurrentPage < Page.TotalPages() ?(Page.CurrentPage + 1):Page.CurrentPage)" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        }
                    </li>
                </ul>
            </nav>
        </div>

    </div>
</div>

@section Scripts{
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
}

shopapp.webui/Views/Shop/Search.cshtml
@model ProductListViewModel

<div class="row mt-3">
    <div class="col-md-3">
        @await Component.InvokeAsync("Categories")
        <partial name="_search" />
    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach (var product in Model.Products)
            {
                <div class="col-md-4">
                    @await Html.PartialAsync("_product", product)
                </div>
            }
        </div>
    </div>
</div>

@section Scripts{
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
}